# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-31 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
